add_newline = false

format = """\
    $username\
    $hostname\
    $nodejs\
    $rust\
    $custom\
    $cmd_duration\
    $git_branch\
    $git_state\
    $line_break\
    $directory\
    $character\
"""

scan_timeout = 10

[hostname]
ssh_only = false
format = "[$hostname]($style) ⟫ "
trim_at = ".local"

[git_branch]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "
disabled = true
