[[plugins]]
repo = 'prettier/vim-prettier'
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
let g:vim_markdown_fenced_languages = ["js=javascript", "ts=typescript", "py=python", "rb=ruby", "go", "yaml", "yml", "toml", "json"]
let g:vim_markdown_folding_disabled=1
'''
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'Dockerfile'
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'